### ISSUE TITLE
第一章关于延迟含义的探讨

### ISSUE THREAD

**Issue by xyohn** [DistSysCorp/ddia#16]
作者好，在第一章文中，描述性能章节里对**延迟**有下述描述:
`日常中，延迟经常和响应时间混用指代响应时间；但严格来说，延迟只是**只**请求过程中排队等休眠时间，虽然其在响应时间中一般占大头；但只有我们把请求真正处理耗时认为是瞬时，延迟才能等同于响应时间。`
个人有以下疑问
1.  此处的**只**是否应为**指**？
2. 后文的`请求过程中排队**等**休眠时间`中的**等**的含义是 等待 还是 等等其它(诸如此类)

谢谢

**Comment by songpengwei** [comment]
1. 确实是“指”
2. 是后者，等等其他的意思。

**Comment by xyohn** [comment]
好的明白，谢谢
