### ISSUE TITLE
“Zigzag编码”链接失效

### ISSUE THREAD

**Issue by qilingzhao** [DistSysCorp/ddia#2]
https://ddia.qtmuniao.com/#/ch04 的 [Thrift 和 Protocol Buffers](https://ddia.qtmuniao.com/#/ch04?id=thrift-%e5%92%8c-protocol-buffers) 部分的“Zigzag编码”点击链接到 [404 - Not found
](https://ddia.qtmuniao.com/#/img/ch04-fig04.png)

**Comment by songpengwei** [comment]
谢谢指出，已经 fixed：[963e231e6f9c53df0e11cd035362010e21b46ee0](https://github.com/DistSysCorp/ddia/commit/963e231e6f9c53df0e11cd035362010e21b46ee0)
