### ISSUE TITLE
第五章 EC 方式可以加下相关链接

### ISSUE THREAD

**Issue by qilingzhao** [DistSysCorp/ddia#4]
如题

**Comment by songpengwei** [comment]
> 如题

能大概指出下多少行吗？

**Comment by qilingzhao** [comment]
> > 如题
> 
> 能大概指出下多少行吗？

不好意思，现在才看到这条回复。

我刚看到这里的时候，没有搞懂这里的EC指的是什么，在分布式学习交流群里咨询后得知是“一种冗余编码”，希望这里能加上EC相关的内容链接。

**Comment by qilingzhao** [comment]
在 https://github.com/DistSysCorp/ddia/blob/main/ch05.md 的第 13 行

**Comment by QingZ11** [comment]
> 在 https://github.com/DistSysCorp/ddia/blob/main/ch05.md 的第 13 行

已经加上链接了，下次你可以自己提交 pr 加链接或者是修改 typo，修改措辞呀。
