### ISSUE TITLE
第一章节的小typo

### ISSUE THREAD

**Issue by hengjiaqi** [DistSysCorp/ddia#8]
[这里](https://github.com/DistSysCorp/ddia/blob/main/ch01.md?plain=1#L167)有一个typo, 应该是“事先”而不是“实现”

**Comment by hengjiaqi** [comment]
Happy to fix this and contribute more. Please add me as a contributor if that works for you.

**Comment by songpengwei** [comment]
@hengjiaqi you can create a pr, and I'll merge them, then you will be the contributor automatically.

**Comment by songpengwei** [comment]
fixed
